name: webgl_fundamentals_m3
description: Various 2d math functions used in the WebGL Fundamentals tutorials.
version: 0.1.0
homepage: https://github.com/ALMaclaine/dart_webgl_fundamentals_m3

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  effective_dart: ^1.2.1
  test: ^1.14.4
